Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:39 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:07:41 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 208, in play
    print('\nFrom Play [index]: ' + i)
TypeError: can only concatenate str (not "int") to str

Error logged at: 01:21:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 219, in play
    if check:
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\discord\abc.py", line 856, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\discord\http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client.py", line 480, in _request
    conn = await self._connector.connect(
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\connector.py", line 526, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

Error logged at: 01:27:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 221, in play
    nowPlayingIndex = i
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\discord\abc.py", line 856, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\discord\http.py", line 165, in request
    async with self.__session.request(method, url, **kwargs) as r:
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client.py", line 504, in _request
    await resp.start(conn)
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "C:\Program Files (x86)\Python38-32\lib\site-packages\aiohttp\streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2683)

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:04 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:33:06 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    if not voice_client.is_playing():
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:31 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:31 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:31 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:32 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:33 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 01:38:34 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 212, in play
    ytUrl = getYtLink(tracks[i])
AttributeError: 'NoneType' object has no attribute 'is_playing'

Error logged at: 02:05:05 05-04-2020
Error details as printed by python: 
Traceback (most recent call last):
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 215, in play
    ytUrl = getYtLink(tracks[i])
  File "D:\Projects\Python\Personal\Discord Music bot\DiscordMusicBot.py", line 107, in getYtLink
    return ("http://www.youtube.com/watch?v=" + search_results[0]) #print the youtube video url followed by the first 11 digit identifer found by filter
IndexError: list index out of range

